# Build stage
FROM node:latest AS builder

WORKDIR /app

COPY package*.json ./
COPY .env ./

RUN npm ci

COPY . .

RUN npm run build

# Production stage
FROM node:latest

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.env ./

COPY --from=builder /app/src/modules/wrappers/mailer/templates ./dist/modules/wrappers/mailer/templates

USER node

EXPOSE 3000

ENV NODE_ENV=production

CMD ["npm", "run", "start:prod"]