services:
  inventory-db:
    image: postgres:latest
    container_name: inventory-db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-demo}
    ports:
      - "${DB_PORT:-5455}:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data

volumes:
  inventory_postgres_data:
