version: '3.8'

services:
  inventory_api:
    container_name: inventory_api
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '3333:3000'
    networks:
      - logistics_network
    restart: unless-stopped
networks:
  logistics_network:
    external: true
